process.env.DB_CLIENT = "pg";
process.env.DB_HOST = "localhost";
process.env.DB_PORT = "5432";
process.env.DB_USER = "postgres";
process.env.DB_PASS = process.env.DB_PASSWORD || "";
process.env.DB_DATABASE = "studenthub_test";
process.env.SESSION_SECRET = "test-secret";
process.env.NODE_ENV = "test";
process.env.FRONTEND_URL = "http://localhost:30010";
